# Generated by Django 4.1.4 on 2022-12-17 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macro_app', '0002_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='macros',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='macro_app.macros'),
        ),
    ]
