# Generated by Django 4.1.4 on 2022-12-17 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macro_app', '0003_food_macros'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
