# Generated by Django 4.1.4 on 2022-12-17 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macro_app', '0004_delete_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('macros', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='macro_app.macros')),
            ],
        ),
    ]
